Update Run-Tests.yml

diff --git a/.github/workflows/Run-Tests.yml b/.github/workflows/Run-Tests.yml
--- a/.github/workflows/Run-Tests.yml
+++ b/.github/workflows/Run-Tests.yml
@@ -69,7 +69,13 @@ jobs:
       - name: Run Cucumber Tests
         run: |
           echo "Running tests with tags: ${{ inputs.test_cucumber_tags }}"
-          mvn clean test -Dcucumber.filter.tags="${{ inputs.test_cucumber_tags }}" -DENVIRONMENT=${{ inputs.test_env }} -DCONFIG_SOURCE=doppler -DDOPPLER_PROJECT_NAME=${{ inputs.test_doppler_project_name }} -DDOPPLER_SERVICE_TOKEN=${{ secrets.test_doppler_service_token }}
+          mvn clean test -Dcucumber.filter.tags="${{ inputs.test_cucumber_tags }}" -DENVIRONMENT=${{ inputs.test_env }} -DCONFIG_SOURCE=doppler -DDOPPLER_PROJECT_NAME=${{ inputs.test_doppler_project_name }} -DDOPPLER_SERVICE_TOKEN=${{ secrets.test_doppler_service_token }} || TEST_FAILED=true
+
+          if [ "$TEST_FAILED" = "true" ]; then
+            echo "TEST_STATUS=FAILED" >> $GITHUB_ENV
+          else
+            echo "TEST_STATUS=SUCCESS" >> $GITHUB_ENV
+          fi
         continue-on-error: true
         
       - name: Upload Test Results
@@ -78,9 +84,12 @@ jobs:
           name: test-results
           path: target/cucumber.json
       
-      - name: Tests Failed
-        if: failure()
-        run: exit 1
+      - name: Tests Result
+        run: |
+          echo "Test Status: $TEST_STATUS"
+          if [ "$TEST_STATUS" = "FAILED" ]; then
+            exit 1
+          fi
           
   upload_test_result:
     name: 'Upload Test Results'
